[project]
name = "gcp-log-transformer"
version = "0.1.0"
description = "Parses and tranforms/aggregate GCP logs before streaming."
requires-python = ">=3.10"
dependencies = ["python-dateutil", "PyYAML>=6.0"]

[tool.setuptools]
packages = ["src"]
